services:
  db:
    image: postgres:16
    container_name: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
      - TZ=Europe/Moscow
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  bll-server:
    build: bll-server
    image: shateit-bll-server
    container_name: shareit-bll-server
    expose:
      - "8888"
#      - "8080"
#    ports:
#      - "8888:8888"
#      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit
      - LOGGING_LEVEL_RU_PRACTICUM=DEBUG
      - TZ=Europe/Moscow

  gateway:
#    build:
#      context: .
#      dockerfile: gateway/Dockerfile
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    expose:
      - "8080"
    ports:
      - "8080:8080"
#      - "8000:8000"
    depends_on:
      bll-server:
        condition: service_started
    environment:
      - SERVER_PORT=8080
      - SHAREIT_SERVER_URL=http://bll-server:8888
      - LOGGING_LEVEL_RU_PRACTICUM=DEBUG
      - TZ=Europe/Moscow

