
create table if not exists users (
    id bigint generated by default as identity not null,
    name varchar(255),
    surname varchar(255),
    email varchar(512) not null,
    constraint pk_user primary key (id),
    constraint uq_user_email unique (email)
);

create table if not exists items (
    id bigint generated by default as identity not null,
    name varchar(255) not null,
    description varchar(255),
    available boolean not null,
    owner_id bigint references users(id)
);
